In [1]:
import numpy as np
from scipy.stats import norm
from scipy.special import comb
import matplotlib.pyplot as plt
import pandas as pd
import random

In [2]:
def calculate_portfolio_returns(file_path):
    # Read the Excel file
    xls = pd.ExcelFile(file_path)
    
    # Initialize dictionaries to store data
    stock_data = {}
    monthly_returns_data = {}
    pb_ratio_data = {}

    # Process each sheet in the Excel file
    for sheet_name in xls.sheet_names:
        df = pd.read_excel(xls, sheet_name)
        filtered_df = df[df['Date'] >= '2011-06-01']
        filtered_df.set_index('Date', inplace=True)

        mom_returns = filtered_df["mom_return"]
        stock_data[sheet_name] = mom_returns

        monthly_returns = (filtered_df['close'] - filtered_df['current_price']) / filtered_df['current_price']
        monthly_returns_data[sheet_name] = monthly_returns

        pb_ratios = filtered_df['PB_ratio']
        pb_ratio_data[sheet_name] = pb_ratios

    # Consolidate data
    consolidated_data = pd.DataFrame(stock_data)
    consolidated_monthly_returns = pd.DataFrame(monthly_returns_data)
    consolidated_pb_ratios = pd.DataFrame(pb_ratio_data)

    # Momentum-based ranking and calculations
    ranked_data_mom = consolidated_data.rank(axis=1, ascending=True)
    mean_rank_mom = ranked_data_mom.mean(axis=1)
    rank_difference_mom = ranked_data_mom.subtract(mean_rank_mom, axis=0)
    scaling_factor_mom = 2 / rank_difference_mom.abs().sum(axis=1)
    weighted_ranks_mom = rank_difference_mom.multiply(scaling_factor_mom, axis=0)
    portfolio_returns_mom = consolidated_monthly_returns * weighted_ranks_mom
    total_portfolio_returns_mom = portfolio_returns_mom.sum(axis=1)

    # PB Ratio-based ranking and calculations
    ranked_value = consolidated_pb_ratios.rank(axis=1, ascending=False)
    mean_rank_value = ranked_value.mean(axis=1)
    rank_difference_value = ranked_value.subtract(mean_rank_value, axis=0)
    scaling_factor_value = 2 / rank_difference_value.abs().sum(axis=1)
    weighted_ranks_value = rank_difference_value.multiply(scaling_factor_value, axis=0)
    portfolio_returns_value = consolidated_monthly_returns * weighted_ranks_value
    total_portfolio_returns_value = portfolio_returns_value.sum(axis=1)

    # Calculate correlation
    correlation = total_portfolio_returns_value.corr(total_portfolio_returns_mom)

    return total_portfolio_returns_mom, total_portfolio_returns_value, correlation

In [3]:
mom_portolios = {}
value_portfolios = {}
correlation = []
for i in ["TW_equity.xlsx","JP_equity.xlsx","US_equity.xlsx","Global_equity_indice.xlsx"]:
    portf = calculate_portfolio_returns(i)
    mom_portolios[i] = portf[0]
    value_portfolios[i] = portf[1]
    correlation.append(portf[2])
    
consolidated_mom = pd.DataFrame(mom_portolios)
consolidated_value = pd.DataFrame(value_portfolios)

In [4]:
correlation

[-0.3651761562012506,
 -0.3789055111343172,
 -0.5190093313074965,
 -0.1519344849885108]

In [5]:
consolidated_mom

,TW_equity.xlsx,JP_equity.xlsx,US_equity.xlsx,Global_equity_indice.xlsx
Date,,,,
2011-06-01,0.039395,-0.006580,-0.068574,-0.050030
2011-07-01,0.145492,0.114394,-0.129509,0.032057
2011-08-01,-0.101197,0.103788,-0.004223,0.109041
2011-09-01,0.038891,0.069708,0.049031,0.199535
2011-10-01,-0.045418,-0.040652,-0.087106,-0.272586
...,...,...,...,...
2023-08-01,0.014026,-0.038484,0.033524,0.053342
2023-09-01,-0.025518,-0.053767,-0.028212,0.017517
2023-10-01,-0.018314,-0.004031,0.040473,0.111299
2023-11-01,0.014521,0.120719,-0.025539,-0.035142
2023-12-01,0.075293,-0.021208,0.028159,-0.176000

In [6]:
consolidated_value

,TW_equity.xlsx,JP_equity.xlsx,US_equity.xlsx,Global_equity_indice.xlsx
Date,,,,
2011-06-01,0.054273,-0.035876,-0.092546,-0.010192
2011-07-01,-0.037894,-0.081314,-0.079569,-0.032057
2011-08-01,-0.028473,-0.135938,0.030538,-0.109041
2011-09-01,-0.161923,-0.072959,-0.040273,-0.161348
2011-10-01,0.069194,0.070128,0.063920,0.255555
...,...,...,...,...
2023-08-01,-0.019428,0.012392,-0.011951,-0.040210
2023-09-01,0.030704,0.066109,0.034459,-0.023990
2023-10-01,0.050236,0.024706,0.035132,-0.111299
2023-11-01,-0.028388,-0.103212,-0.025570,0.030776
2023-12-01,-0.058817,0.023060,-0.016786,0.146816

In [7]:
consolidated_mom.columns = [names.replace(".xlsx","") for names in consolidated_mom.columns]
consolidated_value.columns = [names.replace(".xlsx","") for names in consolidated_value.columns]

In [8]:
xls = pd.ExcelFile("Global_government_bonds.xlsx")

In [9]:
# Dictionary to hold data for each stock
stock_data = {}
monthly_returns_data = {}
pb_ratio_data = {}
# Iterate through each sheet (representing each company)
for sheet_name in xls.sheet_names:
    # Read the specific sheet
    df = pd.read_excel(xls, sheet_name)

    # Filter rows where date is on or after 2011-06-01
    filtered_df = df[df['Date'] >= '2011-06-01']
    
    # Set the 'Date' column as the index
    filtered_df.set_index('Date', inplace=True)

    # Extract the 'mom_return' column
    mom_returns = filtered_df["mom_return"]
    stock_data[sheet_name] = mom_returns
    
    monthly_returns = filtered_df["return"]
    monthly_returns_data[sheet_name] = monthly_returns
    
    pb_ratios = filtered_df['PB_ratio']

    # Store the PB_ratio data with the date as index
    pb_ratio_data[sheet_name] = pb_ratios


bonds_data = pd.DataFrame(stock_data)
bonds_monthly_returns = pd.DataFrame(monthly_returns_data)
bonds_pb_ratios = pd.DataFrame(pb_ratio_data)

In [10]:
ranked_data_mom = bonds_data.rank(axis=1, ascending=True)
ranked_data_mom  # Display the first few rows of the correctly ranked data

             TW   US   JP
Date
2011-06-01  2.0  3.0  1.0
2011-07-01  2.0  3.0  1.0
2011-08-01  2.0  3.0  1.0
2011-09-01  2.0  3.0  1.0
2011-10-01  2.0  3.0  1.0
...         ...  ...  ...
2023-08-01  2.0  3.0  1.0
2023-09-01  2.0  3.0  1.0
2023-10-01  2.0  3.0  1.0
2023-11-01  2.0  3.0  1.0
2023-12-01  2.0  3.0  1.0

[151 rows x 3 columns]

In [11]:
# For the PB_ratio ranking, calculate the weights for each stock using the formula c_t * (rank(Sit) - mean(St))
# where c_t is a scaling factor that ensures the overall portfolio is scaled to one dollar long and one dollar short.

# Step 1: Calculate the mean rank for each month across all stocks
mean_rank_mom = ranked_data_mom.mean(axis=1)

# Step 2: Compute the difference between each stock's rank and the mean rank for that day
rank_difference_mom = ranked_data_mom.subtract(mean_rank_mom, axis=0)

# Step 3: Determine c_t for each day
# To find c_t, we ensure that the sum of positive weights equals 1 (one dollar long)
# and the sum of negative weights equals -1 (one dollar short).

# The sum of absolute values of rank differences should equal 2 (1 for positive and 1 for negative)
scaling_factor_mom = 2 / rank_difference_mom.abs().sum(axis=1)

# Apply the scaling factor to each stock's rank difference
weighted_ranks_mom = rank_difference_mom.multiply(scaling_factor_mom, axis=0)

weighted_ranks_mom # Display the first few rows of weighted ranks

             TW   US   JP
Date
2011-06-01  0.0  1.0 -1.0
2011-07-01  0.0  1.0 -1.0
2011-08-01  0.0  1.0 -1.0
2011-09-01  0.0  1.0 -1.0
2011-10-01  0.0  1.0 -1.0
...         ...  ...  ...
2023-08-01  0.0  1.0 -1.0
2023-09-01  0.0  1.0 -1.0
2023-10-01  0.0  1.0 -1.0
2023-11-01  0.0  1.0 -1.0
2023-12-01  0.0  1.0 -1.0

[151 rows x 3 columns]

In [12]:
portfolio_returns_mom = bonds_monthly_returns * weighted_ranks_mom
total_portfolio_returns_mom = portfolio_returns_mom.apply(sum,1)
total_portfolio_returns_mom

Date
2011-06-01    0.02025
2011-07-01    0.01714
2011-08-01    0.01202
2011-09-01    0.00885
2011-10-01    0.01066
               ...
2023-08-01    0.03455
2023-09-01    0.03808
2023-10-01    0.03975
2023-11-01    0.03654
2023-12-01    0.03250
Length: 151, dtype: float64

In [13]:
consolidated_mom["Global_government_bonds"] = total_portfolio_returns_mom

In [14]:
# Rank the PB_ratio for each company on each day
# The highest PB_ratio gets the highest rank (largest number) and the lowest gets the lowest rank

ranked_value = bonds_pb_ratios.rank(axis=1, ascending=False)
ranked_value  # Display the first few rows of the ranked PB_ratios

             TW   US   JP
Date
2011-06-01  1.0  3.0  2.0
2011-07-01  1.0  3.0  2.0
2011-08-01  1.0  3.0  2.0
2011-09-01  2.0  3.0  1.0
2011-10-01  1.0  3.0  2.0
...         ...  ...  ...
2023-08-01  3.0  1.0  2.0
2023-09-01  3.0  1.0  2.0
2023-10-01  3.0  1.0  2.0
2023-11-01  3.0  1.0  2.0
2023-12-01  3.0  1.0  2.0

[151 rows x 3 columns]

In [15]:
# For the PB_ratio ranking, calculate the weights for each stock using the formula c_t * (rank(Sit) - mean(St))
# where c_t is a scaling factor that ensures the overall portfolio is scaled to one dollar long and one dollar short.

# Step 1: Calculate the mean rank for each day across all stocks in the PB_ratio ranking
mean_rank_value = ranked_value.mean(axis=1)

# Step 2: Compute the difference between each stock's rank and the mean rank for that day in the PB_ratio ranking
rank_difference_value = ranked_value.subtract(mean_rank_value, axis=0)

# Step 3: Determine c_t for each day in the PB_ratio ranking
# The sum of absolute values of rank differences should equal 2 (1 for positive and 1 for negative)
scaling_factor_value = 2 / rank_difference_value.abs().sum(axis=1)

# Apply the scaling factor to each stock's rank difference in the PB_ratio ranking
weighted_ranks_value = rank_difference_value.multiply(scaling_factor_value, axis=0)

weighted_ranks_value  # Display the first few rows of weighted ranks for the PB_ratio ranki

             TW   US   JP
Date
2011-06-01 -1.0  1.0  0.0
2011-07-01 -1.0  1.0  0.0
2011-08-01 -1.0  1.0  0.0
2011-09-01  0.0  1.0 -1.0
2011-10-01 -1.0  1.0  0.0
...         ...  ...  ...
2023-08-01  1.0 -1.0  0.0
2023-09-01  1.0 -1.0  0.0
2023-10-01  1.0 -1.0  0.0
2023-11-01  1.0 -1.0  0.0
2023-12-01  1.0 -1.0  0.0

[151 rows x 3 columns]

In [16]:
portfolio_returns_value = bonds_monthly_returns * weighted_ranks_value
total_portfolio_returns_value = portfolio_returns_value.apply(sum,1)
total_portfolio_returns_value

Date
2011-06-01    0.01650
2011-07-01    0.01193
2011-08-01    0.00784
2011-09-01    0.00885
2011-10-01    0.00741
               ...
2023-08-01   -0.02931
2023-09-01   -0.03353
2023-10-01   -0.03631
2023-11-01   -0.03045
2023-12-01   -0.02666
Length: 151, dtype: float64

In [17]:
consolidated_value["Global_government_bonds"] = total_portfolio_returns_value

In [18]:
consolidated_value

,TW_equity,JP_equity,US_equity,Global_equity_indice,Global_government_bonds
Date,,,,,
2011-06-01,0.054273,-0.035876,-0.092546,-0.010192,0.01650
2011-07-01,-0.037894,-0.081314,-0.079569,-0.032057,0.01193
2011-08-01,-0.028473,-0.135938,0.030538,-0.109041,0.00784
2011-09-01,-0.161923,-0.072959,-0.040273,-0.161348,0.00885
2011-10-01,0.069194,0.070128,0.063920,0.255555,0.00741
...,...,...,...,...,...
2023-08-01,-0.019428,0.012392,-0.011951,-0.040210,-0.02931
2023-09-01,0.030704,0.066109,0.034459,-0.023990,-0.03353
2023-10-01,0.050236,0.024706,0.035132,-0.111299,-0.03631
2023-11-01,-0.028388,-0.103212,-0.025570,0.030776,-0.03045
2023-12-01,-0.058817,0.023060,-0.016786,0.146816,-0.02666

In [19]:
consolidated_mom

,TW_equity,JP_equity,US_equity,Global_equity_indice,Global_government_bonds
Date,,,,,
2011-06-01,0.039395,-0.006580,-0.068574,-0.050030,0.02025
2011-07-01,0.145492,0.114394,-0.129509,0.032057,0.01714
2011-08-01,-0.101197,0.103788,-0.004223,0.109041,0.01202
2011-09-01,0.038891,0.069708,0.049031,0.199535,0.00885
2011-10-01,-0.045418,-0.040652,-0.087106,-0.272586,0.01066
...,...,...,...,...,...
2023-08-01,0.014026,-0.038484,0.033524,0.053342,0.03455
2023-09-01,-0.025518,-0.053767,-0.028212,0.017517,0.03808
2023-10-01,-0.018314,-0.004031,0.040473,0.111299,0.03975
2023-11-01,0.014521,0.120719,-0.025539,-0.035142,0.03654
2023-12-01,0.075293,-0.021208,0.028159,-0.176000,0.03250

In [20]:
# Calculate the correlation between these two series
correlation_bond = total_portfolio_returns_value.corr(total_portfolio_returns_mom)
correlation_bond

-0.8264248134968503

In [22]:
correlation.append(correlation_bond)
correlation

[-0.3651761562012506,
 -0.3789055111343172,
 -0.5190093313074965,
 -0.1519344849885108,
 -0.8264248134968503]

In [23]:
consolidated_mom.to_excel("mom_factor.xlsx")

In [24]:
consolidated_value.to_excel("value_factor.xlsx")

In [ ]:
# mom_everywhere factor portfolio

In [2]:
data = pd.read_excel("mom_factor.xlsx") 
data.set_index('Date', inplace=True)
data

,TW_equity,JP_equity,US_equity,Global_equity_indice,Global_government_bonds
Date,,,,,
2011-06-01,0.039395,-0.006580,-0.068574,-0.050030,0.02025
2011-07-01,0.145492,0.114394,-0.129509,0.032057,0.01714
2011-08-01,-0.101197,0.103788,-0.004223,0.109041,0.01202
2011-09-01,0.038891,0.069708,0.049031,0.199535,0.00885
2011-10-01,-0.045418,-0.040652,-0.087106,-0.272586,0.01066
...,...,...,...,...,...
2023-08-01,0.014026,-0.038484,0.033524,0.053342,0.03455
2023-09-01,-0.025518,-0.053767,-0.028212,0.017517,0.03808
2023-10-01,-0.018314,-0.004031,0.040473,0.111299,0.03975
2023-11-01,0.014521,0.120719,-0.025539,-0.035142,0.03654
2023-12-01,0.075293,-0.021208,0.028159,-0.176000,0.03250

In [3]:
# Calculating the rolling annual volatility for TW_equity, JP_equity, and US_equity
# Assuming the data is monthly, so using a 12-month window for annual volatility
# Volatility is typically calculated as the standard deviation of returns

# Calculating rolling annual volatility for each equity column
data['TW_equity_vol'] = data['TW_equity'].rolling(window=12).std() * (12**0.5)
data['JP_equity_vol'] = data['JP_equity'].rolling(window=12).std() * (12**0.5)
data['US_equity_vol'] = data['US_equity'].rolling(window=12).std() * (12**0.5)
data['Global_equity_vol'] = data['Global_equity_indice'].rolling(window=12).std() * (12**0.5)
data['Global_government_bonds_vol'] = data['Global_government_bonds'].rolling(window=12).std() * (12**0.5)

# Calculating the rolling correlation between the equities
data['TW_JP_corr'] = data['TW_equity'].rolling(window=12).corr(data['JP_equity'])
data['TW_US_corr'] = data['TW_equity'].rolling(window=12).corr(data['US_equity'])
data['JP_US_corr'] = data['JP_equity'].rolling(window=12).corr(data['US_equity'])

# Displaying the first few rows of the dataset with the new columns
data

,TW_equity,JP_equity,US_equity,Global_equity_indice,Global_government_bonds,TW_equity_vol,JP_equity_vol,US_equity_vol,Global_equity_vol,Global_government_bonds_vol,TW_JP_corr,TW_US_corr,JP_US_corr
Date,,,,,,,,,,,,,
2011-06-01,0.039395,-0.006580,-0.068574,-0.050030,0.02025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-07-01,0.145492,0.114394,-0.129509,0.032057,0.01714,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-08-01,-0.101197,0.103788,-0.004223,0.109041,0.01202,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-09-01,0.038891,0.069708,0.049031,0.199535,0.00885,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-10-01,-0.045418,-0.040652,-0.087106,-0.272586,0.01066,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-08-01,0.014026,-0.038484,0.033524,0.053342,0.03455,0.387389,0.330629,0.385682,0.208058,0.007888,0.569902,0.408672,0.337715
2023-09-01,-0.025518,-0.053767,-0.028212,0.017517,0.03808,0.387393,0.321242,0.376955,0.210970,0.008842,0.568284,0.398675,0.302067
2023-10-01,-0.018314,-0.004031,0.040473,0.111299,0.03975,0.383784,0.285764,0.365692,0.245455,0.009819,0.555009,0.449205,0.510998
2023-11-01,0.014521,0.120719,-0.025539,-0.035142,0.03654,0.324118,0.270846,0.345776,0.207810,0.010147,0.312779,0.343749,0.351496
2023-12-01,0.075293,-0.021208,0.028159,-0.176000,0.03250,0.325463,0.272632,0.292685,0.270889,0.010266,0.291658,0.357642,0.384071

In [4]:
# Filtering the data to include only rows where the volatility columns have values
filtered_data = data.dropna(subset=['TW_equity_vol', 'JP_equity_vol', 'US_equity_vol'])

# Displaying the filtered data
filtered_data.head()

,TW_equity,JP_equity,US_equity,Global_equity_indice,Global_government_bonds,TW_equity_vol,JP_equity_vol,US_equity_vol,Global_equity_vol,Global_government_bonds_vol,TW_JP_corr,TW_US_corr,JP_US_corr
Date,,,,,,,,,,,,,
2012-05-01,0.025564,0.038430,0.014237,0.124114,0.00734,0.250782,0.285886,0.226890,0.464593,0.013105,0.080506,-0.325999,-0.109209
2012-06-01,-0.016927,-0.116254,-0.058677,-0.037745,0.00804,0.249965,0.312034,0.225186,0.462998,0.009105,0.120365,-0.289967,-0.050120
2012-07-01,-0.075556,0.064565,-0.009510,0.029133,0.00672,0.209421,0.295535,0.195992,0.462868,0.006001,-0.241487,0.001431,0.191663
2012-08-01,-0.029318,0.046790,0.008569,-0.081438,0.00750,0.187537,0.277643,0.197353,0.458295,0.005562,-0.096705,0.021349,0.201838
2012-09-01,0.027349,-0.034229,0.068973,0.112578,0.00860,0.184800,0.264414,0.205418,0.423000,0.005578,-0.205110,0.019248,0.060445

In [5]:
# Calculating the volatility-weighted values for TW_equity, JP_equity, and US_equity
# The weights are inversely proportional to the volatility, i.e., lower volatility gets higher weight

# Computing the inverse of the volatilities
inverse_volatility = 1 / filtered_data[['TW_equity_vol', 'JP_equity_vol', 'US_equity_vol']]

# Normalizing the inverse volatilities so that they sum up to 1 (to form a proper weight)
weights = inverse_volatility.divide(inverse_volatility.sum(axis=1), axis=0)

# Adding the calculated weights to the dataframe
weighted_data = filtered_data.join(weights, rsuffix='_weight')

# Displaying the updated dataframe with the new weight columns
weighted_data.head()

,TW_equity,JP_equity,US_equity,Global_equity_indice,Global_government_bonds,TW_equity_vol,JP_equity_vol,US_equity_vol,Global_equity_vol,Global_government_bonds_vol,TW_JP_corr,TW_US_corr,JP_US_corr,TW_equity_vol_weight,JP_equity_vol_weight,US_equity_vol_weight
Date,,,,,,,,,,,,,,,,
2012-05-01,0.025564,0.038430,0.014237,0.124114,0.00734,0.250782,0.285886,0.226890,0.464593,0.013105,0.080506,-0.325999,-0.109209,0.335288,0.294118,0.370595
2012-06-01,-0.016927,-0.116254,-0.058677,-0.037745,0.00804,0.249965,0.312034,0.225186,0.462998,0.009105,0.120365,-0.289967,-0.050120,0.343510,0.275180,0.381310
2012-07-01,-0.075556,0.064565,-0.009510,0.029133,0.00672,0.209421,0.295535,0.195992,0.462868,0.006001,-0.241487,0.001431,0.191663,0.360084,0.255161,0.384755
2012-08-01,-0.029318,0.046790,0.008569,-0.081438,0.00750,0.187537,0.277643,0.197353,0.458295,0.005562,-0.096705,0.021349,0.201838,0.380848,0.257248,0.361904
2012-09-01,0.027349,-0.034229,0.068973,0.112578,0.00860,0.184800,0.264414,0.205418,0.423000,0.005578,-0.205110,0.019248,0.060445,0.384833,0.268961,0.346206

In [6]:
# Calculating the portfolio return using the volatility weights for each equity
# The portfolio return is the sum of the product of the returns and their respective weights

weighted_data['stock_momentum_return'] = (weighted_data['TW_equity'] * weighted_data['TW_equity_vol_weight'] +
                                     weighted_data['JP_equity'] * weighted_data['JP_equity_vol_weight'] +
                                     weighted_data['US_equity'] * weighted_data['US_equity_vol_weight'])

# Displaying the updated dataframe with the Portfolio_Return column
weighted_data

,TW_equity,JP_equity,US_equity,Global_equity_indice,Global_government_bonds,TW_equity_vol,JP_equity_vol,US_equity_vol,Global_equity_vol,Global_government_bonds_vol,TW_JP_corr,TW_US_corr,JP_US_corr,TW_equity_vol_weight,JP_equity_vol_weight,US_equity_vol_weight,stock_momentum_return
Date,,,,,,,,,,,,,,,,,
2012-05-01,0.025564,0.038430,0.014237,0.124114,0.00734,0.250782,0.285886,0.226890,0.464593,0.013105,0.080506,-0.325999,-0.109209,0.335288,0.294118,0.370595,0.025150
2012-06-01,-0.016927,-0.116254,-0.058677,-0.037745,0.00804,0.249965,0.312034,0.225186,0.462998,0.009105,0.120365,-0.289967,-0.050120,0.343510,0.275180,0.381310,-0.060180
2012-07-01,-0.075556,0.064565,-0.009510,0.029133,0.00672,0.209421,0.295535,0.195992,0.462868,0.006001,-0.241487,0.001431,0.191663,0.360084,0.255161,0.384755,-0.014391
2012-08-01,-0.029318,0.046790,0.008569,-0.081438,0.00750,0.187537,0.277643,0.197353,0.458295,0.005562,-0.096705,0.021349,0.201838,0.380848,0.257248,0.361904,0.003972
2012-09-01,0.027349,-0.034229,0.068973,0.112578,0.00860,0.184800,0.264414,0.205418,0.423000,0.005578,-0.205110,0.019248,0.060445,0.384833,0.268961,0.346206,0.025198
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-08-01,0.014026,-0.038484,0.033524,0.053342,0.03455,0.387389,0.330629,0.385682,0.208058,0.007888,0.569902,0.408672,0.337715,0.314852,0.368903,0.316245,0.000821
2023-09-01,-0.025518,-0.053767,-0.028212,0.017517,0.03808,0.387393,0.321242,0.376955,0.210970,0.008842,0.568284,0.398675,0.302067,0.309252,0.372934,0.317815,-0.036909
2023-10-01,-0.018314,-0.004031,0.040473,0.111299,0.03975,0.383784,0.285764,0.365692,0.245455,0.009819,0.555009,0.449205,0.510998,0.294769,0.395878,0.309353,0.005526
2023-11-01,0.014521,0.120719,-0.025539,-0.035142,0.03654,0.324118,0.270846,0.345776,0.207810,0.010147,0.312779,0.343749,0.351496,0.319076,0.381834,0.299090,0.043089
2023-12-01,0.075293,-0.021208,0.028159,-0.176000,0.03250,0.325463,0.272632,0.292685,0.270889,0.010266,0.291658,0.357642,0.384071,0.302501,0.361120,0.336379,0.024590

In [7]:
vol_port = np.sqrt((weighted_data["TW_equity_vol_weight"] * weighted_data["TW_equity_vol"])**2 +(weighted_data["US_equity_vol_weight"] * weighted_data["US_equity_vol"])**2 + (weighted_data["JP_equity_vol_weight"] * weighted_data["JP_equity_vol"])**2 + 2* weighted_data["TW_equity_vol"]* weighted_data["JP_equity_vol"] * weighted_data["TW_JP_corr"] * weighted_data["TW_equity_vol_weight"]* weighted_data["JP_equity_vol_weight"] + 2* weighted_data["TW_equity_vol"]* weighted_data["US_equity_vol"] * weighted_data["TW_US_corr"] * weighted_data["TW_equity_vol_weight"]* weighted_data["US_equity_vol_weight"] + 2* weighted_data["JP_equity_vol"]* weighted_data["US_equity_vol"] * weighted_data["JP_US_corr"] * weighted_data["JP_equity_vol_weight"]* weighted_data["US_equity_vol_weight"])
weighted_data["stock_momentum_vol"] = vol_port
weighted_data

,TW_equity,JP_equity,US_equity,Global_equity_indice,Global_government_bonds,TW_equity_vol,JP_equity_vol,US_equity_vol,Global_equity_vol,Global_government_bonds_vol,TW_JP_corr,TW_US_corr,JP_US_corr,TW_equity_vol_weight,JP_equity_vol_weight,US_equity_vol_weight,stock_momentum_return,stock_momentum_vol
Date,,,,,,,,,,,,,,,,,,
2012-05-01,0.025564,0.038430,0.014237,0.124114,0.00734,0.250782,0.285886,0.226890,0.464593,0.013105,0.080506,-0.325999,-0.109209,0.335288,0.294118,0.370595,0.025150,0.127259
2012-06-01,-0.016927,-0.116254,-0.058677,-0.037745,0.00804,0.249965,0.312034,0.225186,0.462998,0.009105,0.120365,-0.289967,-0.050120,0.343510,0.275180,0.381310,-0.060180,0.137400
2012-07-01,-0.075556,0.064565,-0.009510,0.029133,0.00672,0.209421,0.295535,0.195992,0.462868,0.006001,-0.241487,0.001431,0.191663,0.360084,0.255161,0.384755,-0.014391,0.128488
2012-08-01,-0.029318,0.046790,0.008569,-0.081438,0.00750,0.187537,0.277643,0.197353,0.458295,0.005562,-0.096705,0.021349,0.201838,0.380848,0.257248,0.361904,0.003972,0.128818
2012-09-01,0.027349,-0.034229,0.068973,0.112578,0.00860,0.184800,0.264414,0.205418,0.423000,0.005578,-0.205110,0.019248,0.060445,0.384833,0.268961,0.346206,0.025198,0.117916
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-08-01,0.014026,-0.038484,0.033524,0.053342,0.03455,0.387389,0.330629,0.385682,0.208058,0.007888,0.569902,0.408672,0.337715,0.314852,0.368903,0.316245,0.000821,0.289472
2023-09-01,-0.025518,-0.053767,-0.028212,0.017517,0.03808,0.387393,0.321242,0.376955,0.210970,0.008842,0.568284,0.398675,0.302067,0.309252,0.372934,0.317815,-0.036909,0.281930
2023-10-01,-0.018314,-0.004031,0.040473,0.111299,0.03975,0.383784,0.285764,0.365692,0.245455,0.009819,0.555009,0.449205,0.510998,0.294769,0.395878,0.309353,0.005526,0.277807
2023-11-01,0.014521,0.120719,-0.025539,-0.035142,0.03654,0.324118,0.270846,0.345776,0.207810,0.010147,0.312779,0.343749,0.351496,0.319076,0.381834,0.299090,0.043089,0.231621
2023-12-01,0.075293,-0.021208,0.028159,-0.176000,0.03250,0.325463,0.272632,0.292685,0.270889,0.010266,0.291658,0.357642,0.384071,0.302501,0.361120,0.336379,0.024590,0.221612

In [8]:
weighted_data["TW_equity"].corr(weighted_data["JP_equity"]),weighted_data["TW_equity"].corr(weighted_data["US_equity"]),weighted_data["US_equity"].corr(weighted_data["JP_equity"])

(0.1891529385869644, 0.00912604002890081, -0.05465079063887175)

In [9]:
np.mean(weighted_data["TW_JP_corr"]),np.mean(weighted_data["TW_US_corr"]),np.mean(weighted_data["JP_US_corr"])

(0.139546167354588, -0.13030086577387, -0.016335270205904254)

In [10]:
# Dropping the weights, individual volatilities, and correlations from the dataframe
columns_to_drop = [
    "TW_equity_vol", "JP_equity_vol", "US_equity_vol", 
    "TW_equity_vol_weight", "JP_equity_vol_weight", "US_equity_vol_weight", 
    "TW_JP_corr", "TW_US_corr", "JP_US_corr"
]
weighted_data = weighted_data.drop(columns=columns_to_drop)

# Displaying the updated dataframe
weighted_data.head()

,TW_equity,JP_equity,US_equity,Global_equity_indice,Global_government_bonds,Global_equity_vol,Global_government_bonds_vol,stock_momentum_return,stock_momentum_vol
Date,,,,,,,,,
2012-05-01,0.025564,0.038430,0.014237,0.124114,0.00734,0.464593,0.013105,0.025150,0.127259
2012-06-01,-0.016927,-0.116254,-0.058677,-0.037745,0.00804,0.462998,0.009105,-0.060180,0.137400
2012-07-01,-0.075556,0.064565,-0.009510,0.029133,0.00672,0.462868,0.006001,-0.014391,0.128488
2012-08-01,-0.029318,0.046790,0.008569,-0.081438,0.00750,0.458295,0.005562,0.003972,0.128818
2012-09-01,0.027349,-0.034229,0.068973,0.112578,0.00860,0.423000,0.005578,0.025198,0.117916

In [11]:
# Calculating the inverse of the volatilities for each asset
inverse_volatility = 1 / weighted_data[['Global_equity_vol', 'Global_government_bonds_vol', 'stock_momentum_vol']]

# Normalizing the inverse volatilities so that they sum up to 1
weights = inverse_volatility.divide(inverse_volatility.sum(axis=1), axis=0)

# Adding the calculated weights to the dataframe
weighted_data = weighted_data.join(weights, rsuffix='_weight')

# Calculating the portfolio return using the volatility weights for each asset
weighted_data['mom_everywhere'] = (
    weighted_data['Global_equity_indice'] * weighted_data['Global_equity_vol_weight'] +
    weighted_data['Global_government_bonds'] * weighted_data['Global_government_bonds_vol_weight'] +
    weighted_data['stock_momentum_return'] * weighted_data['stock_momentum_vol_weight']
)

# Displaying the updated dataframe with new weights and portfolio return

weighted_data.head()

,TW_equity,JP_equity,US_equity,Global_equity_indice,Global_government_bonds,Global_equity_vol,Global_government_bonds_vol,stock_momentum_return,stock_momentum_vol,Global_equity_vol_weight,Global_government_bonds_vol_weight,stock_momentum_vol_weight,mom_everywhere
Date,,,,,,,,,,,,,
2012-05-01,0.025564,0.038430,0.014237,0.124114,0.00734,0.464593,0.013105,0.025150,0.127259,0.024936,0.884028,0.091036,0.011873
2012-06-01,-0.016927,-0.116254,-0.058677,-0.037745,0.00804,0.462998,0.009105,-0.060180,0.137400,0.018110,0.920866,0.061025,0.003048
2012-07-01,-0.075556,0.064565,-0.009510,0.029133,0.00672,0.462868,0.006001,-0.014391,0.128488,0.012236,0.943687,0.044078,0.006064
2012-08-01,-0.029318,0.046790,0.008569,-0.081438,0.00750,0.458295,0.005562,0.003972,0.128818,0.011501,0.947584,0.040915,0.006333
2012-09-01,0.027349,-0.034229,0.068973,0.112578,0.00860,0.423000,0.005578,0.025198,0.117916,0.012434,0.942960,0.044606,0.010633

In [13]:
# Selecting only the required columns
weighted_data = weighted_data[[
    "TW_equity", "JP_equity", "US_equity", 
    "Global_equity_indice", "Global_government_bonds", 
    "stock_momentum_return", "mom_everywhere"
]]
# Displaying the updated dataframe
weighted_data.head()

,TW_equity,JP_equity,US_equity,Global_equity_indice,Global_government_bonds,stock_momentum_return,mom_everywhere
Date,,,,,,,
2012-05-01,0.025564,0.038430,0.014237,0.124114,0.00734,0.025150,0.011873
2012-06-01,-0.016927,-0.116254,-0.058677,-0.037745,0.00804,-0.060180,0.003048
2012-07-01,-0.075556,0.064565,-0.009510,0.029133,0.00672,-0.014391,0.006064
2012-08-01,-0.029318,0.046790,0.008569,-0.081438,0.00750,0.003972,0.006333
2012-09-01,0.027349,-0.034229,0.068973,0.112578,0.00860,0.025198,0.010633

In [14]:
weighted_data.to_excel("mom_factor_all.xlsx")

In [15]:
# value_everywhere factor portfolio

In [27]:
data = pd.read_excel("value_factor.xlsx") 
data.set_index('Date', inplace=True)
data

,TW_equity,JP_equity,US_equity,Global_equity_indice,Global_government_bonds
Date,,,,,
2011-06-01,0.054273,-0.035876,-0.092546,-0.010192,0.01650
2011-07-01,-0.037894,-0.081314,-0.079569,-0.032057,0.01193
2011-08-01,-0.028473,-0.135938,0.030538,-0.109041,0.00784
2011-09-01,-0.161923,-0.072959,-0.040273,-0.161348,0.00885
2011-10-01,0.069194,0.070128,0.063920,0.255555,0.00741
...,...,...,...,...,...
2023-08-01,-0.019428,0.012392,-0.011951,-0.040210,-0.02931
2023-09-01,0.030704,0.066109,0.034459,-0.023990,-0.03353
2023-10-01,0.050236,0.024706,0.035132,-0.111299,-0.03631
2023-11-01,-0.028388,-0.103212,-0.025570,0.030776,-0.03045
2023-12-01,-0.058817,0.023060,-0.016786,0.146816,-0.02666

In [28]:
# Calculating the rolling annual volatility for TW_equity, JP_equity, and US_equity
# Assuming the data is monthly, so using a 12-month window for annual volatility
# Volatility is typically calculated as the standard deviation of returns

# Calculating rolling annual volatility for each equity column
data['TW_equity_vol'] = data['TW_equity'].rolling(window=12).std() * (12**0.5)
data['JP_equity_vol'] = data['JP_equity'].rolling(window=12).std() * (12**0.5)
data['US_equity_vol'] = data['US_equity'].rolling(window=12).std() * (12**0.5)
data['Global_equity_vol'] = data['Global_equity_indice'].rolling(window=12).std() * (12**0.5)
data['Global_government_bonds_vol'] = data['Global_government_bonds'].rolling(window=12).std() * (12**0.5)

# Calculating the rolling correlation between the equities
data['TW_JP_corr'] = data['TW_equity'].rolling(window=12).corr(data['JP_equity'])
data['TW_US_corr'] = data['TW_equity'].rolling(window=12).corr(data['US_equity'])
data['JP_US_corr'] = data['JP_equity'].rolling(window=12).corr(data['US_equity'])

# Displaying the first few rows of the dataset with the new columns
data

,TW_equity,JP_equity,US_equity,Global_equity_indice,Global_government_bonds,TW_equity_vol,JP_equity_vol,US_equity_vol,Global_equity_vol,Global_government_bonds_vol,TW_JP_corr,TW_US_corr,JP_US_corr
Date,,,,,,,,,,,,,
2011-06-01,0.054273,-0.035876,-0.092546,-0.010192,0.01650,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-07-01,-0.037894,-0.081314,-0.079569,-0.032057,0.01193,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-08-01,-0.028473,-0.135938,0.030538,-0.109041,0.00784,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-09-01,-0.161923,-0.072959,-0.040273,-0.161348,0.00885,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-10-01,0.069194,0.070128,0.063920,0.255555,0.00741,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-08-01,-0.019428,0.012392,-0.011951,-0.040210,-0.02931,0.258188,0.329889,0.243663,0.245291,0.019132,0.097777,-0.461544,0.119587
2023-09-01,0.030704,0.066109,0.034459,-0.023990,-0.03353,0.263379,0.347219,0.254961,0.234051,0.018334,0.160411,-0.350472,0.207161
2023-10-01,0.050236,0.024706,0.035132,-0.111299,-0.03631,0.277314,0.348685,0.254229,0.245302,0.017391,0.196484,-0.193599,0.320889
2023-11-01,-0.028388,-0.103212,-0.025570,0.030776,-0.03045,0.259909,0.349602,0.193410,0.233037,0.016653,0.148475,0.048529,0.541142
2023-12-01,-0.058817,0.023060,-0.016786,0.146816,-0.02666,0.251749,0.356850,0.194226,0.292340,0.015169,0.122734,0.053268,0.550352

In [29]:
# Filtering the data to include only rows where the volatility columns have values
filtered_data = data.dropna(subset=['TW_equity_vol', 'JP_equity_vol', 'US_equity_vol'])

# Displaying the filtered data
filtered_data.head()

,TW_equity,JP_equity,US_equity,Global_equity_indice,Global_government_bonds,TW_equity_vol,JP_equity_vol,US_equity_vol,Global_equity_vol,Global_government_bonds_vol,TW_JP_corr,TW_US_corr,JP_US_corr
Date,,,,,,,,,,,,,
2012-05-01,0.004257,-0.178192,0.018213,-0.200162,0.00734,0.236546,0.315367,0.197514,0.458293,0.010092,-0.020005,0.050154,-0.038822
2012-06-01,0.004953,-0.009618,0.003976,0.092781,0.00804,0.224899,0.315830,0.182088,0.471858,0.006931,-0.004729,0.222182,-0.046563
2012-07-01,-0.056265,-0.097105,0.045770,-0.060208,0.00672,0.227020,0.319183,0.174681,0.474090,0.006472,0.018144,0.151832,-0.196601
2012-08-01,-0.037935,-0.062514,-0.020987,0.080688,0.00750,0.227424,0.299981,0.171781,0.470075,0.006523,0.020063,0.164550,-0.117871
2012-09-01,0.050498,-0.015765,-0.025340,0.072996,0.00860,0.182348,0.294778,0.169190,0.438080,0.006515,-0.127698,-0.016392,-0.163819

In [30]:
# Calculating the volatility-weighted values for TW_equity, JP_equity, and US_equity
# The weights are inversely proportional to the volatility, i.e., lower volatility gets higher weight

# Computing the inverse of the volatilities
inverse_volatility = 1 / filtered_data[['TW_equity_vol', 'JP_equity_vol', 'US_equity_vol']]

# Normalizing the inverse volatilities so that they sum up to 1 (to form a proper weight)
weights = inverse_volatility.divide(inverse_volatility.sum(axis=1), axis=0)

# Adding the calculated weights to the dataframe
weighted_data = filtered_data.join(weights, rsuffix='_weight')

# Displaying the updated dataframe with the new weight columns
weighted_data.head()

,TW_equity,JP_equity,US_equity,Global_equity_indice,Global_government_bonds,TW_equity_vol,JP_equity_vol,US_equity_vol,Global_equity_vol,Global_government_bonds_vol,TW_JP_corr,TW_US_corr,JP_US_corr,TW_equity_vol_weight,JP_equity_vol_weight,US_equity_vol_weight
Date,,,,,,,,,,,,,,,,
2012-05-01,0.004257,-0.178192,0.018213,-0.200162,0.00734,0.236546,0.315367,0.197514,0.458293,0.010092,-0.020005,0.050154,-0.038822,0.339249,0.254459,0.406292
2012-06-01,0.004953,-0.009618,0.003976,0.092781,0.00804,0.224899,0.315830,0.182088,0.471858,0.006931,-0.004729,0.222182,-0.046563,0.339306,0.241615,0.419079
2012-07-01,-0.056265,-0.097105,0.045770,-0.060208,0.00672,0.227020,0.319183,0.174681,0.474090,0.006472,0.018144,0.151832,-0.196601,0.332128,0.236228,0.431644
2012-08-01,-0.037935,-0.062514,-0.020987,0.080688,0.00750,0.227424,0.299981,0.171781,0.470075,0.006523,0.020063,0.164550,-0.117871,0.324460,0.245982,0.429558
2012-09-01,0.050498,-0.015765,-0.025340,0.072996,0.00860,0.182348,0.294778,0.169190,0.438080,0.006515,-0.127698,-0.016392,-0.163819,0.370870,0.229418,0.399713

In [31]:
# Calculating the portfolio return using the volatility weights for each equity
# The portfolio return is the sum of the product of the returns and their respective weights

weighted_data['stock_value_return'] = (weighted_data['TW_equity'] * weighted_data['TW_equity_vol_weight'] +
                                     weighted_data['JP_equity'] * weighted_data['JP_equity_vol_weight'] +
                                     weighted_data['US_equity'] * weighted_data['US_equity_vol_weight'])

# Displaying the updated dataframe with the Portfolio_Return column
weighted_data

,TW_equity,JP_equity,US_equity,Global_equity_indice,Global_government_bonds,TW_equity_vol,JP_equity_vol,US_equity_vol,Global_equity_vol,Global_government_bonds_vol,TW_JP_corr,TW_US_corr,JP_US_corr,TW_equity_vol_weight,JP_equity_vol_weight,US_equity_vol_weight,stock_value_return
Date,,,,,,,,,,,,,,,,,
2012-05-01,0.004257,-0.178192,0.018213,-0.200162,0.00734,0.236546,0.315367,0.197514,0.458293,0.010092,-0.020005,0.050154,-0.038822,0.339249,0.254459,0.406292,-0.036498
2012-06-01,0.004953,-0.009618,0.003976,0.092781,0.00804,0.224899,0.315830,0.182088,0.471858,0.006931,-0.004729,0.222182,-0.046563,0.339306,0.241615,0.419079,0.001023
2012-07-01,-0.056265,-0.097105,0.045770,-0.060208,0.00672,0.227020,0.319183,0.174681,0.474090,0.006472,0.018144,0.151832,-0.196601,0.332128,0.236228,0.431644,-0.021870
2012-08-01,-0.037935,-0.062514,-0.020987,0.080688,0.00750,0.227424,0.299981,0.171781,0.470075,0.006523,0.020063,0.164550,-0.117871,0.324460,0.245982,0.429558,-0.036701
2012-09-01,0.050498,-0.015765,-0.025340,0.072996,0.00860,0.182348,0.294778,0.169190,0.438080,0.006515,-0.127698,-0.016392,-0.163819,0.370870,0.229418,0.399713,0.004983
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-08-01,-0.019428,0.012392,-0.011951,-0.040210,-0.02931,0.258188,0.329889,0.243663,0.245291,0.019132,0.097777,-0.461544,0.119587,0.351832,0.275362,0.372805,-0.007879
2023-09-01,0.030704,0.066109,0.034459,-0.023990,-0.03353,0.263379,0.347219,0.254961,0.234051,0.018334,0.160411,-0.350472,0.207161,0.358223,0.271726,0.370050,0.041714
2023-10-01,0.050236,0.024706,0.035132,-0.111299,-0.03631,0.277314,0.348685,0.254229,0.245302,0.017391,0.196484,-0.193599,0.320889,0.346486,0.275565,0.377948,0.037492
2023-11-01,-0.028388,-0.103212,-0.025570,0.030776,-0.03045,0.259909,0.349602,0.193410,0.233037,0.016653,0.148475,0.048529,0.541142,0.323912,0.240810,0.435279,-0.045180
2023-12-01,-0.058817,0.023060,-0.016786,0.146816,-0.02666,0.251749,0.356850,0.194226,0.292340,0.015169,0.122734,0.053268,0.550352,0.333152,0.235030,0.431818,-0.021424

In [32]:
vol_port = np.sqrt((weighted_data["TW_equity_vol_weight"] * weighted_data["TW_equity_vol"])**2 +(weighted_data["US_equity_vol_weight"] * weighted_data["US_equity_vol"])**2 + (weighted_data["JP_equity_vol_weight"] * weighted_data["JP_equity_vol"])**2 + 2* weighted_data["TW_equity_vol"]* weighted_data["JP_equity_vol"] * weighted_data["TW_JP_corr"] * weighted_data["TW_equity_vol_weight"]* weighted_data["JP_equity_vol_weight"] + 2* weighted_data["TW_equity_vol"]* weighted_data["US_equity_vol"] * weighted_data["TW_US_corr"] * weighted_data["TW_equity_vol_weight"]* weighted_data["US_equity_vol_weight"] + 2* weighted_data["JP_equity_vol"]* weighted_data["US_equity_vol"] * weighted_data["JP_US_corr"] * weighted_data["JP_equity_vol_weight"]* weighted_data["US_equity_vol_weight"])
weighted_data["stock_value_vol"] = vol_port
weighted_data

,TW_equity,JP_equity,US_equity,Global_equity_indice,Global_government_bonds,TW_equity_vol,JP_equity_vol,US_equity_vol,Global_equity_vol,Global_government_bonds_vol,TW_JP_corr,TW_US_corr,JP_US_corr,TW_equity_vol_weight,JP_equity_vol_weight,US_equity_vol_weight,stock_value_return,stock_value_vol
Date,,,,,,,,,,,,,,,,,,
2012-05-01,0.004257,-0.178192,0.018213,-0.200162,0.00734,0.236546,0.315367,0.197514,0.458293,0.010092,-0.020005,0.050154,-0.038822,0.339249,0.254459,0.406292,-0.036498,0.138591
2012-06-01,0.004953,-0.009618,0.003976,0.092781,0.00804,0.224899,0.315830,0.182088,0.471858,0.006931,-0.004729,0.222182,-0.046563,0.339306,0.241615,0.419079,0.001023,0.139498
2012-07-01,-0.056265,-0.097105,0.045770,-0.060208,0.00672,0.227020,0.319183,0.174681,0.474090,0.006472,0.018144,0.151832,-0.196601,0.332128,0.236228,0.431644,-0.021870,0.129432
2012-08-01,-0.037935,-0.062514,-0.020987,0.080688,0.00750,0.227424,0.299981,0.171781,0.470075,0.006523,0.020063,0.164550,-0.117871,0.324460,0.245982,0.429558,-0.036701,0.130620
2012-09-01,0.050498,-0.015765,-0.025340,0.072996,0.00860,0.182348,0.294778,0.169190,0.438080,0.006515,-0.127698,-0.016392,-0.163819,0.370870,0.229418,0.399713,0.004983,0.104422
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-08-01,-0.019428,0.012392,-0.011951,-0.040210,-0.02931,0.258188,0.329889,0.243663,0.245291,0.019132,0.097777,-0.461544,0.119587,0.351832,0.275362,0.372805,-0.007879,0.143963
2023-09-01,0.030704,0.066109,0.034459,-0.023990,-0.03353,0.263379,0.347219,0.254961,0.234051,0.018334,0.160411,-0.350472,0.207161,0.358223,0.271726,0.370050,0.041714,0.164345
2023-10-01,0.050236,0.024706,0.035132,-0.111299,-0.03631,0.277314,0.348685,0.254229,0.245302,0.017391,0.196484,-0.193599,0.320889,0.346486,0.275565,0.377948,0.037492,0.183509
2023-11-01,-0.028388,-0.103212,-0.025570,0.030776,-0.03045,0.259909,0.349602,0.193410,0.233037,0.016653,0.148475,0.048529,0.541142,0.323912,0.240810,0.435279,-0.045180,0.178117
2023-12-01,-0.058817,0.023060,-0.016786,0.146816,-0.02666,0.251749,0.356850,0.194226,0.292340,0.015169,0.122734,0.053268,0.550352,0.333152,0.235030,0.431818,-0.021424,0.176979

In [33]:
weighted_data["TW_equity"].corr(weighted_data["JP_equity"]),weighted_data["TW_equity"].corr(weighted_data["US_equity"]),weighted_data["US_equity"].corr(weighted_data["JP_equity"])

(-0.08008759210939237, 0.0053148775460582776, -0.0712022524065633)

In [34]:
np.mean(weighted_data["TW_JP_corr"]),np.mean(weighted_data["TW_US_corr"]),np.mean(weighted_data["JP_US_corr"])

(-0.13010501372127517, -0.029003833785933825, -0.11948979311785474)

In [35]:
# Dropping the weights, individual volatilities, and correlations from the dataframe
columns_to_drop = [
    "TW_equity_vol", "JP_equity_vol", "US_equity_vol", 
    "TW_equity_vol_weight", "JP_equity_vol_weight", "US_equity_vol_weight", 
    "TW_JP_corr", "TW_US_corr", "JP_US_corr"
]
weighted_data = weighted_data.drop(columns=columns_to_drop)

# Displaying the updated dataframe
weighted_data.head()

,TW_equity,JP_equity,US_equity,Global_equity_indice,Global_government_bonds,Global_equity_vol,Global_government_bonds_vol,stock_value_return,stock_value_vol
Date,,,,,,,,,
2012-05-01,0.004257,-0.178192,0.018213,-0.200162,0.00734,0.458293,0.010092,-0.036498,0.138591
2012-06-01,0.004953,-0.009618,0.003976,0.092781,0.00804,0.471858,0.006931,0.001023,0.139498
2012-07-01,-0.056265,-0.097105,0.045770,-0.060208,0.00672,0.474090,0.006472,-0.021870,0.129432
2012-08-01,-0.037935,-0.062514,-0.020987,0.080688,0.00750,0.470075,0.006523,-0.036701,0.130620
2012-09-01,0.050498,-0.015765,-0.025340,0.072996,0.00860,0.438080,0.006515,0.004983,0.104422

In [36]:
# Calculating the inverse of the volatilities for each asset
inverse_volatility = 1 / weighted_data[['Global_equity_vol', 'Global_government_bonds_vol', 'stock_value_vol']]

# Normalizing the inverse volatilities so that they sum up to 1
weights = inverse_volatility.divide(inverse_volatility.sum(axis=1), axis=0)

# Adding the calculated weights to the dataframe
weighted_data = weighted_data.join(weights, rsuffix='_weight')

# Calculating the portfolio return using the volatility weights for each asset
weighted_data['value_everywhere'] = (
    weighted_data['Global_equity_indice'] * weighted_data['Global_equity_vol_weight'] +
    weighted_data['Global_government_bonds'] * weighted_data['Global_government_bonds_vol_weight'] +
    weighted_data['stock_value_return'] * weighted_data['stock_value_vol_weight']
)

# Displaying the updated dataframe with new weights and portfolio return

weighted_data.head()

,TW_equity,JP_equity,US_equity,Global_equity_indice,Global_government_bonds,Global_equity_vol,Global_government_bonds_vol,stock_value_return,stock_value_vol,Global_equity_vol_weight,Global_government_bonds_vol_weight,stock_value_vol_weight,value_everywhere
Date,,,,,,,,,,,,,
2012-05-01,0.004257,-0.178192,0.018213,-0.200162,0.00734,0.458293,0.010092,-0.036498,0.138591,0.020114,0.913373,0.066513,0.000250
2012-06-01,0.004953,-0.009618,0.003976,0.092781,0.00804,0.471858,0.006931,0.001023,0.139498,0.013800,0.939521,0.046679,0.008882
2012-07-01,-0.056265,-0.097105,0.045770,-0.060208,0.00672,0.474090,0.006472,-0.021870,0.129432,0.012835,0.940151,0.047013,0.004517
2012-08-01,-0.037935,-0.062514,-0.020987,0.080688,0.00750,0.470075,0.006523,-0.036701,0.130620,0.013044,0.940014,0.046942,0.006380
2012-09-01,0.050498,-0.015765,-0.025340,0.072996,0.00860,0.438080,0.006515,0.004983,0.104422,0.013804,0.928282,0.057913,0.009279

In [37]:
# Selecting only the required columns
weighted_data = weighted_data[[
    "TW_equity", "JP_equity", "US_equity", 
    "Global_equity_indice", "Global_government_bonds", 
    "stock_value_return", "value_everywhere"
]]
# Displaying the updated dataframe
weighted_data.head()

,TW_equity,JP_equity,US_equity,Global_equity_indice,Global_government_bonds,stock_value_return,value_everywhere
Date,,,,,,,
2012-05-01,0.004257,-0.178192,0.018213,-0.200162,0.00734,-0.036498,0.000250
2012-06-01,0.004953,-0.009618,0.003976,0.092781,0.00804,0.001023,0.008882
2012-07-01,-0.056265,-0.097105,0.045770,-0.060208,0.00672,-0.021870,0.004517
2012-08-01,-0.037935,-0.062514,-0.020987,0.080688,0.00750,-0.036701,0.006380
2012-09-01,0.050498,-0.015765,-0.025340,0.072996,0.00860,0.004983,0.009279

In [38]:
weighted_data.to_excel("value_factor_all.xlsx")

In [39]:
# more analysis

In [41]:
# Load the Excel files
mom_factor_path = 'mom_factor_all.xlsx'
value_factor_path = 'value_factor_all.xlsx'

mom_factor_df = pd.read_excel(mom_factor_path)
value_factor_df = pd.read_excel(value_factor_path)

In [42]:
mom_factor_df.head()

,Date,TW_equity,JP_equity,US_equity,Global_equity_indice,Global_government_bonds,stock_momentum_return,mom_everywhere
0,2012-05-01,0.025564,0.038430,0.014237,0.124114,0.00734,0.025150,0.011873
1,2012-06-01,-0.016927,-0.116254,-0.058677,-0.037745,0.00804,-0.060180,0.003048
2,2012-07-01,-0.075556,0.064565,-0.009510,0.029133,0.00672,-0.014391,0.006064
3,2012-08-01,-0.029318,0.046790,0.008569,-0.081438,0.00750,0.003972,0.006333
4,2012-09-01,0.027349,-0.034229,0.068973,0.112578,0.00860,0.025198,0.010633

In [43]:
value_factor_df.head()

,Date,TW_equity,JP_equity,US_equity,Global_equity_indice,Global_government_bonds,stock_value_return,value_everywhere
0,2012-05-01,0.004257,-0.178192,0.018213,-0.200162,0.00734,-0.036498,0.000250
1,2012-06-01,0.004953,-0.009618,0.003976,0.092781,0.00804,0.001023,0.008882
2,2012-07-01,-0.056265,-0.097105,0.045770,-0.060208,0.00672,-0.021870,0.004517
3,2012-08-01,-0.037935,-0.062514,-0.020987,0.080688,0.00750,-0.036701,0.006380
4,2012-09-01,0.050498,-0.015765,-0.025340,0.072996,0.00860,0.004983,0.009279

In [44]:
# Merging the dataframes on 'Date' column
combined_df = pd.merge(mom_factor_df, value_factor_df, on='Date')

# Display the first few rows of the combined dataframe to verify the merge
combined_df.head()

,Date,TW_equity_x,JP_equity_x,US_equity_x,Global_equity_indice_x,Global_government_bonds_x,stock_momentum_return,mom_everywhere,TW_equity_y,JP_equity_y,US_equity_y,Global_equity_indice_y,Global_government_bonds_y,stock_value_return,value_everywhere
0,2012-05-01,0.025564,0.038430,0.014237,0.124114,0.00734,0.025150,0.011873,0.004257,-0.178192,0.018213,-0.200162,0.00734,-0.036498,0.000250
1,2012-06-01,-0.016927,-0.116254,-0.058677,-0.037745,0.00804,-0.060180,0.003048,0.004953,-0.009618,0.003976,0.092781,0.00804,0.001023,0.008882
2,2012-07-01,-0.075556,0.064565,-0.009510,0.029133,0.00672,-0.014391,0.006064,-0.056265,-0.097105,0.045770,-0.060208,0.00672,-0.021870,0.004517
3,2012-08-01,-0.029318,0.046790,0.008569,-0.081438,0.00750,0.003972,0.006333,-0.037935,-0.062514,-0.020987,0.080688,0.00750,-0.036701,0.006380
4,2012-09-01,0.027349,-0.034229,0.068973,0.112578,0.00860,0.025198,0.010633,0.050498,-0.015765,-0.025340,0.072996,0.00860,0.004983,0.009279

In [45]:
# Removing the specified columns from the combined dataframe
columns_to_exclude = ['stock_momentum_return', 'mom_everywhere', 'stock_value_return', 'value_everywhere']
filtered_df = combined_df.drop(columns=columns_to_exclude)

# Computing the pair-wise cross-section correlation between two markets
correlation_matrix = filtered_df.corr()

correlation_matrix

,TW_equity_x,JP_equity_x,US_equity_x,Global_equity_indice_x,Global_government_bonds_x,TW_equity_y,JP_equity_y,US_equity_y,Global_equity_indice_y,Global_government_bonds_y
TW_equity_x,1.000000,0.189153,0.009126,0.070307,-0.079608,-0.359822,0.076027,-0.007736,-0.128416,0.079860
JP_equity_x,0.189153,1.000000,-0.054651,0.059245,-0.030917,-0.034904,-0.330545,0.075507,-0.050552,0.025261
US_equity_x,0.009126,-0.054651,1.000000,0.031550,-0.166239,0.032021,0.163081,-0.547831,0.108754,0.100515
Global_equity_indice_x,0.070307,0.059245,0.031550,1.000000,-0.008196,0.121337,0.001124,0.003014,0.062255,0.056285
Global_government_bonds_x,-0.079608,-0.030917,-0.166239,-0.008196,1.000000,-0.043722,0.013858,0.137944,-0.115305,-0.825260
TW_equity_y,-0.359822,-0.034904,0.032021,0.121337,-0.043722,1.000000,-0.080088,0.005315,0.180888,0.093304
JP_equity_y,0.076027,-0.330545,0.163081,0.001124,0.013858,-0.080088,1.000000,-0.071202,0.061476,0.041258
US_equity_y,-0.007736,0.075507,-0.547831,0.003014,0.137944,0.005315,-0.071202,1.000000,-0.154524,-0.113327
Global_equity_indice_y,-0.128416,-0.050552,0.108754,0.062255,-0.115305,0.180888,0.061476,-0.154524,1.000000,0.060528
Global_government_bonds_y,0.079860,0.025261,0.100515,0.056285,-0.825260,0.093304,0.041258,-0.113327,0.060528,1.000000

In [46]:
# Calculating correlation between 'value_everywhere' and 'mom_everywhere'
correlation_value_mom = combined_df['value_everywhere'].corr(combined_df['mom_everywhere'])
correlation_value_mom

-0.48072781272375187

In [47]:
# Calculating the correlation for the specified columns
columns_for_correlation = [
    'stock_momentum_return', 
    'stock_value_return', 
    'Global_equity_indice_x', 
    'Global_government_bonds_x', 
    'Global_equity_indice_y', 
    'Global_government_bonds_y'
]

correlation_matrix_selected = combined_df[columns_for_correlation].corr()
correlation_matrix_selected

,stock_momentum_return,stock_value_return,Global_equity_indice_x,Global_government_bonds_x,Global_equity_indice_y,Global_government_bonds_y
stock_momentum_return,1.000000,-0.266770,0.102700,-0.154577,-0.035428,0.124559
stock_value_return,-0.266770,1.000000,0.064290,0.032103,0.031116,0.036361
Global_equity_indice_x,0.102700,0.064290,1.000000,-0.008196,0.062255,0.056285
Global_government_bonds_x,-0.154577,0.032103,-0.008196,1.000000,-0.115305,-0.825260
Global_equity_indice_y,-0.035428,0.031116,0.062255,-0.115305,1.000000,0.060528
Global_government_bonds_y,0.124559,0.036361,0.056285,-0.825260,0.060528,1.000000